name: rd_loca_news
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  change_app_package_name: ^1.3.0
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.1
  icons_launcher: ^2.1.7
  share_plus: ^9.0.0
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.0
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
