name: rd_loca_news
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
